name: Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-10.15, windows-2019 ]
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]
        include:
          - os: ubuntu-latest
            python-version: 3.9
            artifact: sdist
          - os: ubuntu-latest
            container: 'quay.io/pypa/manylinux2010_x86_64:latest'

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"

      - name: Install dev dependencies
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --user --upgrade wheel "setuptools>=38.6.0" twine milksnake packaging
          python -m pip --version
          python -m wheel version
          python -m twine --version

      - name: Check Python code format
        run: |
          python -m pip install --user black
          python -m black --check ./

      - name: Build source distribution
        run: python setup.py sdist
        if: ${{ matrix.artifact == 'sdist' }}

      - name: Build wheels
        run: python -m pip -vvv wheel . -w wheelhouse/
        if: ${{ matrix.artifact != 'sdist' }}
